/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basics;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class App {

    public static void main(String[] args) {
        // write your code here
        System.out.println("Hello World AYA");

        pluralize("cat", 5);
        flipNHeads(1);
        clock();
    }


    public static void pluralize(String word, int number) {
        if (number == 1) {
            System.out.println("I own " + number + " " + word + ".");
        } else if (number == 0 || number > 1) {
            System.out.println("I own " + number + " " + word + "s.");
        }
    }

    public static void flipNHeads(int n) {
        int flips = 0, countHead = 0;
        if (n < 0) {
            System.out.println("Error");
        } else {
            while (countHead != n) {
                double ranNumber = Math.random();
//                System.out.println(ranNumber);
                if (ranNumber > 0.5) {
                    System.out.println("heads");
                    countHead++;
                    flips++;
                }
                if (ranNumber < 0.5) {
                    System.out.println("tails");
                    countHead = 0;
                    flips++;
                }
            }
            System.out.println("It took " + flips + " flips to flip " + countHead + " heads in a row.");
        }
    }

    public static void clock() {
        int  million = 1_000_000;
        double count = 0.0;
        String time = "";

        while (true) {
            LocalDateTime now = LocalDateTime.now();
            String currentTime = now.format(DateTimeFormatter.ofPattern("HH:mm:ss"));
            if (!currentTime.equals(time)) {
                time = currentTime;
                System.out.println(time + "  " + count/million + " MHz");
                count = 0.0;
            }

            count++;
        }
    }
}