/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.basics;
import java.util.ArrayList;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
            roll(4);
//            int[] array = {5, 9, 2, 1, 9};
//            System.out.println("Is The Array Duplicate ? " + containsDuplicates(array));
//            System.out.println("The Average of Array : "+ calculatingAverages(array));

//        int[][] weeklyMonthTemperatures = {
//                {66, 64, 58, 65, 71, 57, 60},
//                {57, 65, 65, 70, 72, 65, 51},
//                {55, 54, 60, 53, 59, 57, 61},
//                {65, 56, 55, 52, 55, 62, 57}
//        };
//        System.out.println(sum(weeklyMonthTemperatures));
        }

        public static void roll(int n) {
            ArrayList<Integer> result = new ArrayList<>(n);
            int rollNumber = 0;
            for (int index = 0; index < n; index++) {
                rollNumber = (int) (Math.random() * 6 + 1);
                result.add(rollNumber);
            }

            System.out.println("The result of Roll function is  =>  " + result);
        }

        public static boolean containsDuplicates(int[] array) {
            for (int i = 0; i < array.length; i++) {
                for (int j = i + 1; j < array.length; j++) {
                    if (array[i] == array[j])
                        return true;
                }
            }
            return false;
        }

        public static double calculatingAverages(int[] array){
            double sumVaules = 0.0;
            double avgResult = 0.0;
            for (int index = 0; index < array.length; index++) {
                sumVaules += array[index];
            }
            System.out.println(sumVaules);
            avgResult = sumVaules/array.length;
            return  avgResult;
        }









//    public static void ArraysOfArrays (int[][] array)
//    {
//        double sumValues = 0;
//        double[] result = new double[array.length];
//        for (int i = 0; i < array.length; i++) {
//            for (int j = i; j < array.length; j++) {
//                sumValues += array[j][i];
//            }
////            sumValues = 0;
//        }
//        System.out.println(sumValues);
//    }

//
//    public static int[] sum(int[][] array)
//    {
//        int[] sum1 ;
//        for (int row=0; row < array.length; ++row)
//        {
//            for(int col=0; col<array[row].length; ++col)
//            {
//                sum1 = array[row][col];
//            }
//        } return sum1;
//    }
    }


