/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        System.out.println("-------------------------- Restaurant --------------------------");
        Restaurant();
    }


public static void Restaurant() {

    Restaurant restaurant1 = new Restaurant("Vogo", 65.3, 2);
    Review review1 = new Review("Noraml taste" ,"AYA" ,3);
    Review review2 = new Review("Noraml taste" ,"AYA" ,4);
    Review review3 = new Review("GOOOOD taste" ,"AYA" ,5);
    Review review4 = new Review("Ver GOOOD taste" ,"AYA" ,1.6);


    restaurant1.addReview(review1);
    restaurant1.addReview(review2);
    restaurant1.addReview(review3);
    restaurant1.addReview(review4);

    restaurant1.getStars();

    System.out.println(restaurant1.toString());

    }

}
