/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }


    Restaurant restaurant1 = new Restaurant("Vogo", 65.3, 2);
    Review review1 = new Review("Noraml taste" ,"AYA" ,3);
    Review review2 = new Review("Noraml taste" ,"AYA" ,4);
    Review review3 = new Review("GOOOOD taste" ,"AYA" ,5);
    Review review4 = new Review("Ver GOOOD taste" ,"AYA" ,1.6);


    @Test
    void resTset()
    {
        restaurant1.addReview(review1);
        restaurant1.addReview(review2);
        restaurant1.addReview(review3);
        restaurant1.addReview(review4);
    }
    @Test
    void resToString(){
        System.out.println(restaurant1.toString());
    }
    @Test
    void revTest(){
        System.out.println(review1.toString());
    }

}
