/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.basics;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;

class LibraryTest {

    Library classUnderTest;
    int[] arrayTest = {5, 9, 2, 1, 9};


    @BeforeEach
    void setUp() {
        classUnderTest = new Library();
    }

    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }


    @Test
    @DisplayName("contains Duplicates Test")
    void containsDuplicates() {
        boolean result = classUnderTest.containsDuplicates(arrayTest);
        assertEquals(true, result);
    }

    @Test
    @DisplayName("calculating Averages Test")
    void calculatingAverages() {
        double result = classUnderTest.calculatingAverages(arrayTest);
        assertEquals(5.2, result);
    }

}
